version:                            '3'

services:

  deeplearning:

      environment:
        NVIDIA_VISIBLE_DEVICES:     all
        NVIDIA_DRIVER_CAPABILITIES: compute,utility

      networks:
        - network


networks:
  network:
    driver:                         bridge
